services:
  jenkins: 
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /Users/shellyupadhayay/Desktop/node_demo/:/var/jenkins_home
   